item {
  id: 1
  name: 'ballpen'
}

item {
  id: 2
  name: 'tumbler'
}

item {
  id: 3
  name: 'cane'
}

item {
  id: 4
  name: 'car'
}

item {
  id: 5
  name: 'dog'
}

item {
  id: 6
  name: 'gallon'
}

item {
  id: 7
  name: 'glasses'
}

item {
  id: 8
  name: 'laptop'
}

item {
  id: 9
  name: 'facemask'
}

item {
  id: 10
  name: 'remote'
}

item {
  id: 11
  name: 'slipper'
}

item {
  id: 12
  name: 'garbagebin'
}

item {
  id: 13
  name: 'watch'
}

item {
  id: 14
  name: 'hand'
}